import type { Metadata } from "next";
import NavBar from "@/components/NavBar";
import "./globals.css";
import Footer from "@/components/Footer";
import ContextProvider from "@/app/context/ContextProvider";

export const metadata: Metadata = {
  title: "Gm-Route",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <ContextProvider>
          <NavBar></NavBar>
          {children}
          <Footer></Footer>
        </ContextProvider>
      </body>
    </html>
  );
}
